### PR TITLE
ssl: context wrapped listener failed to supply _context in accept()

### PR DESCRIPTION
**Pull request by temoto**
https://github.com/eventlet/eventlet/issues/651

Seems correct, but could potentially break a lot of code, so calling for extensive public testing.

`pip install -U https://github.com/eventlet/eventlet/archive/i651.zip` and try to run your software.

### CODE REVIEW

**Comment by temoto** [comment]
Last version fails on Python 2.7 - 3.6, works on 3.7+.

I'm tired today, will continue later. Error with keyfile argument.

```
Traceback (most recent call last):
  File "/home/travis/build/eventlet/eventlet/tests/ssl_test.py", line 342, in test_context_wrapped_accept
    peer, _ = server_tls.accept()
  File "/home/travis/build/eventlet/eventlet/eventlet/green/ssl.py", line 407, in accept
    keyfile=self.keyfile,
AttributeError: 'GreenSSLSocket' object has no attribute 'keyfile'
```

**Review by jstasiak — APPROVED** [review]
Works for me on Python 3.8.5 and looks reasonable.

**Comment by temoto** [comment]
Works now.

**Comment by jstasiak** [comment]
How does the code work on Python older than 3.8 with `keyfile`, `certfile` not being passed through?

**Comment by temoto** [comment]
@jstasiak 
> How does the code work on Python older than 3.8 with `keyfile`, `certfile` not being passed through?

Sorry, it's a working black magic for me, currently. Test passes, so apparently they are read from context. So I was wondering is it redundant to pass them at all. And can you believe it, all key/cert related kwargs were redundant. It passes py2.7 and 3.7 without extra 3.7 condition. Hope it will pass all tests.

Thank you.

**Comment by temoto** [comment]
@jstasiak and for shorter diff too, I've only noticed it too late after push, was too much excited about dropping cert/key kwargs. Done.

**Review by jstasiak — APPROVED** [review]
Yeah it was just a detail, LGTM regardless.
