### ISSUE TITLE
AttributeError: module 'collections' has no attribute 'MutableMapping'

### ISSUE THREAD

**Issue by k-bx** [eventlet/eventlet#770]
```
root@stardust:~# python3 -m FreeTAKServer.controllers.services.FTS
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/FreeTAKServer/controllers/services/FTS.py", line 14, in <module>
    from FreeTAKServer.controllers.services.TCPDataPackageService import TCPDataPackageService as TCPFlaskFunctions
  File "/usr/local/lib/python3.10/dist-packages/FreeTAKServer/controllers/services/TCPDataPackageService.py", line 1, in <module>
    from .DataPackageServer import FlaskFunctions, Path, dp_directory, os, app, eventlet, const
  File "/usr/local/lib/python3.10/dist-packages/FreeTAKServer/controllers/services/DataPackageServer.py", line 20, in <module>
    import eventlet
  File "/usr/local/lib/python3.10/dist-packages/eventlet/__init__.py", line 17, in <module>
    from eventlet import convenience
  File "/usr/local/lib/python3.10/dist-packages/eventlet/convenience.py", line 7, in <module>
    from eventlet.green import socket
  File "/usr/local/lib/python3.10/dist-packages/eventlet/green/socket.py", line 21, in <module>
    from eventlet.support import greendns
  File "/usr/local/lib/python3.10/dist-packages/eventlet/support/greendns.py", line 66, in <module>
    setattr(dns, pkg, import_patched('dns.' + pkg))
  File "/usr/local/lib/python3.10/dist-packages/eventlet/support/greendns.py", line 61, in import_patched
    return patcher.import_patched(module_name, **modules)
  File "/usr/local/lib/python3.10/dist-packages/eventlet/patcher.py", line 132, in import_patched
    return inject(
  File "/usr/local/lib/python3.10/dist-packages/eventlet/patcher.py", line 109, in inject
    module = __import__(module_name, {}, {}, module_name.split('.')[:-1])
  File "/usr/local/lib/python3.10/dist-packages/dns/namedict.py", line 35, in <module>
    class NameDict(collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'
```

**Comment by fabswt** [comment]
@k-bx Any luck resolving the issue?

**Comment by k-bx** [comment]
@fabswt yes by manually patching like this https://stackoverflow.com/questions/70943244/attributeerror-module-collections-has-no-attribute-mutablemapping but it should be fixed in the library itself

**Comment by tipabu** [comment]
Can you upgrade `dnspython`? It looks like you're on some 1.x version. This should have been fixed by https://github.com/rthalley/dnspython/commit/62d3d41382d919af4662c12876f3de6ca854fd54 a few years ago.

**Comment by k-bx** [comment]
If 1.x is too old, you should up your requirement in setup.py @tipabu 

![0FA020CE-83E4-484D-82C2-EDC817A51B37](https://user-images.githubusercontent.com/107968/213110480-0214816f-e089-47cd-8904-859aa975b775.png)

**Comment by tipabu** [comment]
Our dnspython requirement is accurate: eventlet will work with dnspython 1.15.0. Notably, we need to support such an old dnspython as long as we're continuing to support old versions of Python -- dnspython 2.0.0 dropped support for Python 2.7, 3.4, and 3.5 which eventlet still support.

The issue you're seeing is an incompatibility between dnspython 1.x and Python 3.10 -- try updating dnspython to 2.2.0 or later, which the dnspython maintainers marked as supporting Python 3.10. If upgrading to 2.3.0, note that you'll want eventlet 0.33.3 to pick up https://github.com/eventlet/eventlet/pull/782

**Comment by k-bx** [comment]
I didn't follow Python for a while, but would something like https://peps.python.org/pep-0508/ or any other means be possible to set a python3-specific version?

**Comment by temoto** [comment]
This constraint would be better set in dnspython package, to avoid split-brain situation. Sorry for bad experience.

dnspython 1.x support will soon be dropped transitively with py2.7.

Seems like a resolved question. Feel free to reopen.
